language: java
jdk: oraclejdk8
script: mvn test
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
dd:
- openssl aes-256-cbc -K $encrypted_81e76d1e75c0_key -iv $encrypted_81e76d1e75c0_iv
  -in application.properties.enc -out src/main/resources/application.properties -d
